## Tensorflow - Tensor 다루기

### Tensor 생성법

In [8]:
import tensorflow as tf

In [9]:
# 1 tensor 생성
x = tf.ones(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [10]:
# 0 tensor 생성
x = tf.zeros(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [11]:
# 랜덤 tensor 생성 1
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.9246884 ],
       [ 1.6853868 ],
       [ 0.23186946]], dtype=float32)>

In [12]:
# 랜덤 tensor 생성 2
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.15283883]
 [0.88135386]
 [0.09239089]], shape=(3, 1), dtype=float32)


### Tensor 변수 - 값 변경

**Tensorflow는 Numpy와 다르게 값 변경 불가**

In [15]:
# Numpy
import numpy as np

x = np.ones(shape=(2, 2))
x[0, 0] = 0.
x

array([[0., 1.],
       [1., 1.]])

In [48]:
# Tensorflow
import tensorflow as tf

# Tensorflow는 Tensor 내 특정 위치에 값 할당 불가 -> Tensor 변수 사용하여 해결
v = tf.Variable(initial_value=tf.ones(shape=(2, 2)))
v[0, 0].assign(0.)
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 1.],
       [1., 1.]], dtype=float32)>

**텐서플로 변수에 값 할당하기**

In [35]:
v = tf.Variable(initial_value=tf.ones(shape=(2, 2)))
v.assign(tf.zeros((2, 2)))
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### Tensor 기본 연산

**기본 연산**

In [ ]:
a = tf.Variable(initial_value=tf.ones(shape=(2, 2)))

a.assign_add(tf.ones((2, 2)))       # add

a.assign_sub(tf.ones((2, 2)))       # substract

b = tf.square(a)                    # 제곱

b = tf.sqrt(a)                      # 루트

a = a + b                           # add 

a = a *= b                          # 원소간 곱

a = tf.matmul(a, b)                 # Dot