## Numpy - Tensor 다루기

In [1]:
import numpy as np

### Tensor 생성법

In [2]:
# tensor 생성
a = np.array( [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ] )
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# 0 tensor 생성
a = np.zeros( (3,4) )
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# 1 tensor 생성
a = np.ones( (3,4) )
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# 항등 행렬 tensor 생성
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [6]:
# 랜덤 tensor 생성
a = np.random.random( (3,4) )
a

array([[0.06279092, 0.54308993, 0.34991248, 0.09520045],
       [0.14738087, 0.6203786 , 0.68526406, 0.35361214],
       [0.52891378, 0.01614134, 0.2695091 , 0.89130305]])

In [7]:
# Range tensor 생성
a = np.array(range(1,13))     # [1,2,3,4,5,6,7,8,9,10,11,12]
a = a.reshape((3,4)) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Tensor 차원 다루기

In [8]:
# 차원의 크기
a.shape       # 반드시 tuple 형태

(3, 4)

In [9]:
# 차원의 수
a.ndim       # len(a.shape)   # rank   # dimension

2

In [10]:
# 차원 변경
a = a.reshape( (4, -1) )      # a.reshape( (4, 3) )    # np.reshape( a, (4, -1) )
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
# 1차원
a = a.flatten()
a.shape

(12,)

**차원 확장 기법**

In [12]:
# 차원 확장 (axis = 0 차원 확장)
a = np.array([[1,2,],[3,4],[5,6]])

b = np.expand_dims(a, axis=0)
b = a.reshape((1, *a.shape))
b = a.reshape((1, 3, 2))
b = np.reshape(a, (1, 3, 2))
b = np.array([a])

b

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
# 차원 확장 (axis = -1 차원 확장)
a = np.array([[1,2,],[3,4],[5,6]])

c = np.expand_dims(a, axis = -1)
c = a.reshape( (*a.shape, 1) ) 

c

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

### 데이터 타입 (dtype)

In [ ]:
a = np.array([ [1, 2], [3, 4], [5, 6] ])
a.dtype

dtype('int64')

In [ ]:
# 부동 소수점
b = np.array([ [1., 2.], [3., 4.], [5., 6.] ])
b.dtype

dtype('float64')

In [ ]:
c = np.zeros( (2,2) )
c.dtype

dtype('float64')

### Indexing, Slicing

In [ ]:
# Indexing
a[1, 1:3]         # array([6, 7]),      차원의 수 = 1,  차원 = (2, )
a.ndim

2

In [ ]:
# Slicing
a[1:2, 1:3]       # array([[6, 7]]),    차원의 수 = 2 , 차원 = (1,2)
a.ndim

2

### Filter

In [ ]:
a = np.reshape(np.array( range(1,13) ), (3,4) )

In [ ]:
# 각 원소 조건 return
a % 2 == 1

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [ ]:
# True 조건 원소 return
a[a % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

### Tensor 연산 - Broadcasting

- a + b = np.add(a,b)
- a - b = np.subtract(a,b)
- a * b = np.multiply(a,b)
- a / b = np.divide(a,b)
- np.sqrt(a) -> 루트
- np.maximum(a,b)

In [13]:
# 서로 다른 차원 연산 가능
a = np.array([1, 2, 3])     # 1차원 배열
b = np.array([[1, 2, 3],    # 2차원 배열
              [4, 5, 6]])

c = a + b                   # Broadcasting이 적용된 연산
print(c)

[[2 4 6]
 [5 7 9]]


In [14]:
a = np.array( [ [1,2],[3,4] ] )

In [15]:
# 각 원소별 연산
a + np.array([10])

array([[11, 12],
       [13, 14]])

In [16]:
# 한 행 씩 연산
a + np.array([10,20])

array([[11, 22],
       [13, 24]])

In [17]:
# 매핑되는 각 행에서 한 열 씩 연산
a + np.array([[10],[20]])

array([[11, 12],
       [23, 24]])

**Concatenation**

In [18]:
# concatenation - 수직 (row)
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])

np.concatenate((a,b), axis = 0)     # np.r_[a,b]    # np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [19]:
# concatenation - 수평 (col)
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])

np.concatenate((a,b), axis = 1)     # np.c_[a,b]    # np.hstack((a,b))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

### Matrix multiplication (dot)

In [20]:
x = np.array([[1,2,3],[4,5,6]])
y = x.T
z = x.dot(y)      # np.dot(x, y)
z

array([[14, 32],
       [32, 77]])